### ISSUE TITLE
Display Feedback

### ISSUE THREAD

**Issue by SamH1576** [SamH1576/SearchParty#29]
Display feedback needs to be disabled until after the event, and should we display rows where no comment has been left?

**Comment by SamH1576** [comment]
Feedback is left displaying when a new category of events is loaded.
![image](https://cloud.githubusercontent.com/assets/17874999/21773538/5f133346-d687-11e6-981c-ba209f126c16.png)

**Comment by ministrudels** [comment]
Fixed: Empty comments and ratings were shown for users who had attended the event, but yet to complete feedback form
